<?php

namespace DPRMC\ThomsonReutersDataScopeSelect\Tests;

use PHPUnit\Framework\TestCase;
use DPRMC\ThomsonReutersDataScopeSelect\TRDSSClient;


abstract class AbstractBase extends TestCase {

    const DEBUG = TRUE;

    protected $userName;
    protected $password;

    /**
     * @var TRDSSClient $client
     */
    protected $client;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->userName = getenv( 'TR_USER' );
        $this->password = getenv( 'TR_PASS' );

        $this->client = TRDSSClient::instantiate( $this->userName, $this->password, self::DEBUG );
    }

}