<?php

namespace DPRMC\ThomsonReutersDataScopeSelect\Tests;

use DPRMC\ThomsonReutersDataScopeSelect\TRDSSClient;
use PHPUnit\Framework\TestCase;

class ClientTest extends TestCase {

    protected $userName;
    protected $password;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userName = $_ENV['USER'];
        $this->password = $_ENV['PASS'];
    }


    /**
     * @test
     */
    public function testClientConstructorShouldCreateInstance(){
        $client = new TRDSSClient($this->userName, $this->password);
        $this->assertInstanceOf(TRDSSClient::class, $client);
    }

}